### ISSUE TITLE
Add OctaviOS to Android 12 ROMs

### ISSUE THREAD

**Issue by JanPokorny** [TheDoop/daisy-stuff#11]
OctaviOS has Android 12 builds for daisy:

Download: https://octavi-os.com/downloads (hotlinking not supported, search for "daisy")
XDA thread: https://forum.xda-developers.com/t/rom-12-daisy-octavios-3-0-official.4190367/

**Comment by ket0x4** [comment]
added. thanks

**Comment by JanPokorny** [comment]
@Caticer The date is backwards 😁

**Comment by ket0x4** [comment]
lmao I just realized (I copied the date from their download page)
